### ISSUE TITLE
UIkit support?

### ISSUE THREAD

**Issue by BayramInanc** [hollyoops/RecoilSwift#11]
Any plan for supporting it?

**Comment by AppleTTT** [comment]
> Any plan for supporting it?

not yet

**Comment by AppleTTT** [comment]
maybe we will support UIKit in the. future, but for now, we dont have a plan for it

**Comment by hollyoops** [comment]
@BayramInanc The key point that does not support UIKit for now are:

- The hooks: In UIkit we need to find a way to refresh the UI after the state changes. But ideally, it could support UIkit with the delegate. 

- Recently, We are improving the stability and performance of the library. It's a big and exciting change. after that we may can consider whether we can support UIkit

**Comment by BayramInanc** [comment]
Any improvement for uıkit support?

**Comment by hollyoops** [comment]
Not yet. Because recoil is based on the hooks. It means that we need to introduce hooks into UIKit. however, it's possible to achieve this. but need to take lots of effort. Recently we don't have a plan to do it.

If more and more people want UIkit support. then we will improve the priority.

**Comment by BayramInanc** [comment]
In a large, advanced projects we could not use swiftui because of its some bugs/version releated etc... problems. It would be really great if we support UIKit.

**Comment by BayramInanc** [comment]
Why cannot we use it without hooks?

**Comment by hollyoops** [comment]
Actually, hooks, is not a must-have option. The key point in order to keep the same interface with Facebook. we use hooks, It's better to keep the same API interface for UIKit and swiftUI if possible.

We need to think about how to design it. If we couldn't do it In UIKit, we may use a delegate or callback to render when the state change. （Like Reswift）

current priority:

- Make it more stable
- Improve the performance for large view
- Make more easy to debug (add time travel etc)

**Comment by hollyoops** [comment]
@BayramInanc  UIKit is supported since `v0.3`. Once the documentation is done, we will close this ticket

**Comment by BayramInanc** [comment]
Super excited about it> @BayramInanc  UIKit is supported since `v0.3`. Once the documentation is done, we will close this ticket
